const bcrypt = require("bcryptjs");

// Pre-hash passwords at module load time (sync is fine for a small user list)
const SALT_ROUNDS = 10;

const users = [
    // ─── System Administrator (city-wide access) ───
    {
        id: "user-admin-1",
        name: "Rajesh Kumar",
        username: "rajesh.kumar",
        passwordHash: bcrypt.hashSync("admin123", SALT_ROUNDS),
        role: "admin",
        state: "DL",
        stateName: "Delhi",
        constituency: "DL-ALL",
        constituencyName: "All Delhi",
    },

    // ─── Officers (one per zone) ───
    {
        id: "user-officer-east",
        name: "Priya Sharma",
        username: "priya.sharma",
        passwordHash: bcrypt.hashSync("officer123", SALT_ROUNDS),
        role: "officer",
        state: "DL",
        stateName: "Delhi",
        constituency: "DL-03",
        constituencyName: "East Delhi",
    },
    {
        id: "user-officer-west",
        name: "Vikram Singh Tomar",
        username: "vikram.tomar",
        passwordHash: bcrypt.hashSync("officer123", SALT_ROUNDS),
        role: "officer",
        state: "DL",
        stateName: "Delhi",
        constituency: "DL-06",
        constituencyName: "West Delhi",
    },
    {
        id: "user-officer-north",
        name: "Anjali Gupta",
        username: "anjali.gupta",
        passwordHash: bcrypt.hashSync("officer123", SALT_ROUNDS),
        role: "officer",
        state: "DL",
        stateName: "Delhi",
        constituency: "DL-01",
        constituencyName: "North Delhi",
    },
    {
        id: "user-officer-central",
        name: "Suresh Yadav",
        username: "suresh.yadav",
        passwordHash: bcrypt.hashSync("officer123", SALT_ROUNDS),
        role: "officer",
        state: "DL",
        stateName: "Delhi",
        constituency: "DL-02",
        constituencyName: "Central Delhi",
    },
    {
        id: "user-officer-south",
        name: "Kavita Reddy",
        username: "kavita.reddy",
        passwordHash: bcrypt.hashSync("officer123", SALT_ROUNDS),
        role: "officer",
        state: "DL",
        stateName: "Delhi",
        constituency: "DL-05",
        constituencyName: "South Delhi",
    },

    // ─── Leaders (one per zone) ───
    {
        id: "user-leader-south",
        name: "Dr. Meena Chaudhary",
        username: "meena.chaudhary",
        passwordHash: bcrypt.hashSync("leader123", SALT_ROUNDS),
        role: "leader",
        state: "DL",
        stateName: "Delhi",
        constituency: "DL-05",
        constituencyName: "South Delhi",
    },
    {
        id: "user-leader-west",
        name: "Arun Jaitley Jr.",
        username: "arun.jaitley",
        passwordHash: bcrypt.hashSync("leader123", SALT_ROUNDS),
        role: "leader",
        state: "DL",
        stateName: "Delhi",
        constituency: "DL-06",
        constituencyName: "West Delhi",
    },
    {
        id: "user-leader-north",
        name: "Sunita Devi",
        username: "sunita.devi",
        passwordHash: bcrypt.hashSync("leader123", SALT_ROUNDS),
        role: "leader",
        state: "DL",
        stateName: "Delhi",
        constituency: "DL-01",
        constituencyName: "North Delhi",
    },
    {
        id: "user-leader-east",
        name: "Rakesh Mehta",
        username: "rakesh.mehta",
        passwordHash: bcrypt.hashSync("leader123", SALT_ROUNDS),
        role: "leader",
        state: "DL",
        stateName: "Delhi",
        constituency: "DL-03",
        constituencyName: "East Delhi",
    },
    {
        id: "user-leader-central",
        name: "Dinesh Mohan",
        username: "dinesh.mohan",
        passwordHash: bcrypt.hashSync("leader123", SALT_ROUNDS),
        role: "leader",
        state: "DL",
        stateName: "Delhi",
        constituency: "DL-02",
        constituencyName: "Central Delhi",
    },
];

module.exports = users;
